### ISSUE TITLE
What is "get_body" supposed to return?

### ISSUE THREAD

**Issue by autarch** [rjbs/Email-Abstract#4]
The docs just say "This returns the body as a string."

So for a multipart message is this all the parts, encoded, each with their own headers? Or is this supposed to be the decoded body of one part?

I'm assuming it's the latter, but better docs would be nice.

**Comment by autarch** [comment]
Actually, looking at Email::Sender's few calls to `get_body()` it looks like it actually expects it to return the entire email including headers, so I'm confused.

**Comment by rjbs** [comment]
It is meant to return the bytes following the header-terminating blank.  It isn't often useful, and I have long wanted to make Email::Abstract more MIME-aware.

The two places I found get_body used, it was to add the "Lines" header that is only used by mutt to give an estimate of message length.  In neither case would I expect that to include the full headers.  If you the Lines header better documented somewhere, let me know.

**Comment by autarch** [comment]
I was just guessing at how it was being used. It was confusing. That said, the fact that Courriel now implements this incorrectly doesn't really worry me too much at the moment, though I will fix it at some point.
