### ISSUE TITLE
3.008 fails with MailTools 2.17 on Perl 5.24.0

### ISSUE THREAD

**Issue by abraxxa** [rjbs/Email-Abstract#7]
I guess this is not a Perl 5.24 issue but because I'm reinstalling my whole module stack which current CPAN modules. Might even be a bug in MailTools 2.17:

> [ahartmai@ahartmai-nb:~/.cpanm/work/1463064753.3612/Email-Abstract-3.008$ ]$ prove -vl t/abstractions.t
> t/abstractions.t .. 
> 1..165
> ok 1 - use Email::Abstract;
> ok 2 - the message ends in a CRLF
> # testing Email::MIME with 1.937
> ok 3 - 'wrapped Email::MIME object' isa 'Email::Abstract'
> ok 4 - Subject OK with Email::MIME
> ok 5 - no exception on altering object via Email::Abstract
> ok 6 - Email::MIME: received headers match up list context get_header
> ok 7 - correct stringification of Email::MIME; same as reference object
> ok 8 - correct body length for Email::MIME
> ok 9 - no exception on altering object via Email::Abstract
> ok 10 - set subject and body, restringified ok with Email::MIME
> ok 11 - 'wrapped Email::MIME object' isa 'Email::Abstract'
> ok 12 - Subject OK with Email::MIME
> ok 13 - no exception on altering object via Email::Abstract
> ok 14 - Email::MIME: received headers match up list context get_header
> ok 15 - correct stringification of Email::MIME; same as reference object
> ok 16 - correct body length for Email::MIME
> ok 17 - no exception on altering object via Email::Abstract
> ok 18 - set subject and body, restringified ok with Email::MIME
> ok 19 - Subject OK with Email::MIME
> ok 20 - no exception on altering object via Email::Abstract
> ok 21 - Email::MIME: received headers match up list context get_header
> ok 22 - correct stringification of Email::MIME; same as reference object
> ok 23 - correct body length for Email::MIME
> ok 24 - no exception on altering object via Email::Abstract
> ok 25 - set subject and body, restringified ok with Email::MIME
> # testing Email::Simple with 2.210
> ok 26 - 'wrapped Email::Simple object' isa 'Email::Abstract'
> ok 27 - Subject OK with Email::Simple
> ok 28 - no exception on altering object via Email::Abstract
> ok 29 - Email::Simple: received headers match up list context get_header
> ok 30 - correct stringification of Email::Simple; same as reference object
> ok 31 - correct body length for Email::Simple
> ok 32 - no exception on altering object via Email::Abstract
> ok 33 - set subject and body, restringified ok with Email::Simple
> ok 34 - 'wrapped Email::Simple object' isa 'Email::Abstract'
> ok 35 - Subject OK with Email::Simple
> ok 36 - no exception on altering object via Email::Abstract
> ok 37 - Email::Simple: received headers match up list context get_header
> ok 38 - correct stringification of Email::Simple; same as reference object
> ok 39 - correct body length for Email::Simple
> ok 40 - no exception on altering object via Email::Abstract
> ok 41 - set subject and body, restringified ok with Email::Simple
> ok 42 - Subject OK with Email::Simple
> ok 43 - no exception on altering object via Email::Abstract
> ok 44 - Email::Simple: received headers match up list context get_header
> ok 45 - correct stringification of Email::Simple; same as reference object
> ok 46 - correct body length for Email::Simple
> ok 47 - no exception on altering object via Email::Abstract
> ok 48 - set subject and body, restringified ok with Email::Simple
> ok 49 # skip MIME::Entity: unavailable
> ok 50 # skip MIME::Entity: unavailable
> ok 51 # skip MIME::Entity: unavailable
> ok 52 # skip MIME::Entity: unavailable
> ok 53 # skip MIME::Entity: unavailable
> ok 54 # skip MIME::Entity: unavailable
> ok 55 # skip MIME::Entity: unavailable
> ok 56 # skip MIME::Entity: unavailable
> ok 57 # skip MIME::Entity: unavailable
> ok 58 # skip MIME::Entity: unavailable
> ok 59 # skip MIME::Entity: unavailable
> ok 60 # skip MIME::Entity: unavailable
> ok 61 # skip MIME::Entity: unavailable
> ok 62 # skip MIME::Entity: unavailable
> ok 63 # skip MIME::Entity: unavailable
> ok 64 # skip MIME::Entity: unavailable
> ok 65 # skip MIME::Entity: unavailable
> ok 66 # skip MIME::Entity: unavailable
> ok 67 # skip MIME::Entity: unavailable
> ok 68 # skip MIME::Entity: unavailable
> ok 69 # skip MIME::Entity: unavailable
> ok 70 # skip MIME::Entity: unavailable
> ok 71 # skip MIME::Entity: unavailable
> # testing Mail::Internet with 2.17
> ok 72 - 'wrapped Mail::Internet object' isa 'Email::Abstract'
> ok 73 - Subject OK with Mail::Internet
> ok 74 - no exception on altering object via Email::Abstract
> ok 75 - Mail::Internet: received headers match up list context get_header
> not ok 76 - correct stringification of Mail::Internet; same as reference object
> 
> #   Failed test 'correct stringification of Mail::Internet; same as reference object'
> #   at t/lib/Test/EmailAbstract.pm line 74.
> #          got: ''
> #     expected: 'Joanna, All
> # 
> # Thanks. I got the following response from Fred Tydeman.
> # 
> # On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
> # > Sun's expert in this area after some discussions with a colleague
> # > outside of Sun concluded that for lround, to align with both C99 and SUS
> # > changes of the following form were necessary:
> # > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
> # 
> # -----
> # Andrew Josey                                The Open Group  
> # Austin Group Chair                          Apex Plaza,Forbury Road,
> # Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
> # Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'
> not ok 77 - correct body length for Mail::Internet
> 
> #   Failed test 'correct body length for Mail::Internet'
> #   at t/lib/Test/EmailAbstract.pm line 80.
> #          got: '0'
> #     expected: '749'
> ok 78 - no exception on altering object via Email::Abstract
> ok 79 - set subject and body, restringified ok with Mail::Internet
> ok 80 - 'wrapped Mail::Internet object' isa 'Email::Abstract'
> ok 81 - Subject OK with Mail::Internet
> ok 82 - no exception on altering object via Email::Abstract
> ok 83 - Mail::Internet: received headers match up list context get_header
> not ok 84 - correct stringification of Mail::Internet; same as reference object
> 
> #   Failed test 'correct stringification of Mail::Internet; same as reference object'
> #   at t/lib/Test/EmailAbstract.pm line 74.
> #          got: ''
> #     expected: 'Joanna, All
> # 
> # Thanks. I got the following response from Fred Tydeman.
> # 
> # On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
> # > Sun's expert in this area after some discussions with a colleague
> # > outside of Sun concluded that for lround, to align with both C99 and SUS
> # > changes of the following form were necessary:
> # > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
> # 
> # -----
> # Andrew Josey                                The Open Group  
> # Austin Group Chair                          Apex Plaza,Forbury Road,
> # Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
> # Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'
> not ok 85 - correct body length for Mail::Internet
> 
> #   Failed test 'correct body length for Mail::Internet'
> #   at t/lib/Test/EmailAbstract.pm line 80.
> #          got: '0'
> #     expected: '749'
> ok 86 - no exception on altering object via Email::Abstract
> ok 87 - set subject and body, restringified ok with Mail::Internet
> ok 88 - Subject OK with Mail::Internet
> ok 89 - no exception on altering object via Email::Abstract
> ok 90 - Mail::Internet: received headers match up list context get_header
> not ok 91 - correct stringification of Mail::Internet; same as reference object
> 
> #   Failed test 'correct stringification of Mail::Internet; same as reference object'
> #   at t/lib/Test/EmailAbstract.pm line 74.
> #          got: ''
> #     expected: 'Joanna, All
> # 
> # Thanks. I got the following response from Fred Tydeman.
> # 
> # On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
> # > Sun's expert in this area after some discussions with a colleague
> # > outside of Sun concluded that for lround, to align with both C99 and SUS
> # > changes of the following form were necessary:
> # > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
> # 
> # -----
> # Andrew Josey                                The Open Group  
> # Austin Group Chair                          Apex Plaza,Forbury Road,
> # Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
> # Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'
> not ok 92 - correct body length for Mail::Internet
> 
> #   Failed test 'correct body length for Mail::Internet'
> #   at t/lib/Test/EmailAbstract.pm line 80.
> #          got: '0'
> #     expected: '749'
> ok 93 - no exception on altering object via Email::Abstract
> ok 94 - set subject and body, restringified ok with Mail::Internet
> ok 95 # skip Mail::Message: unavailable
> ok 96 # skip Mail::Message: unavailable
> ok 97 # skip Mail::Message: unavailable
> ok 98 # skip Mail::Message: unavailable
> ok 99 # skip Mail::Message: unavailable
> ok 100 # skip Mail::Message: unavailable
> ok 101 # skip Mail::Message: unavailable
> ok 102 # skip Mail::Message: unavailable
> ok 103 # skip Mail::Message: unavailable
> ok 104 # skip Mail::Message: unavailable
> ok 105 # skip Mail::Message: unavailable
> ok 106 # skip Mail::Message: unavailable
> ok 107 # skip Mail::Message: unavailable
> ok 108 # skip Mail::Message: unavailable
> ok 109 # skip Mail::Message: unavailable
> ok 110 # skip Mail::Message: unavailable
> ok 111 # skip Mail::Message: unavailable
> ok 112 # skip Mail::Message: unavailable
> ok 113 # skip Mail::Message: unavailable
> ok 114 # skip Mail::Message: unavailable
> ok 115 # skip Mail::Message: unavailable
> ok 116 # skip Mail::Message: unavailable
> ok 117 # skip Mail::Message: unavailable
> ok 118 - 'wrapped plaintext object' isa 'Email::Abstract'
> ok 119 - Subject OK with plaintext
> ok 120 - no exception on altering object via Email::Abstract
> ok 121 - plaintext: received headers match up list context get_header
> ok 122 - correct stringification of plaintext; same as reference object
> ok 123 - correct body length for plaintext
> ok 124 - no exception on altering object via Email::Abstract
> ok 125 - set subject and body, restringified ok with plaintext
> ok 126 - Subject OK with plaintext (class)
> ok 127 - can't alter an unwrapped string
> ok 128 - plaintext (class): received headers match up list context get_header
> ok 129 - correct stringification of plaintext (class); same as reference object
> ok 130 - correct body length for plaintext (class)
> ok 131 - can't alter an unwrapped string
> ok 132 - (no test; can't check altering unalterable alteration)
> ok 133 - Subject OK with Email::Abstract
> ok 134 - no exception on altering object via Email::Abstract
> ok 135 - Email::Abstract: received headers match up list context get_header
> ok 136 - correct stringification of Email::Abstract; same as reference object
> ok 137 - correct body length for Email::Abstract
> ok 138 - no exception on altering object via Email::Abstract
> ok 139 - set subject and body, restringified ok with Email::Abstract
> ok 140 - trying to wrap a wrapper returns the wrapper; it doesn't re-wrap
> ok 141 - 'wrapped plaintext (ref) object' isa 'Email::Abstract'
> ok 142 - Subject OK with plaintext (ref)
> ok 143 - no exception on altering object via Email::Abstract
> ok 144 - plaintext (ref): received headers match up list context get_header
> ok 145 - correct stringification of plaintext (ref); same as reference object
> ok 146 - correct body length for plaintext (ref)
> ok 147 - no exception on altering object via Email::Abstract
> ok 148 - set subject and body, restringified ok with plaintext (ref)
> ok 149 - Subject OK with plaintext (ref) (class)
> ok 150 - can't alter an unwrapped string
> ok 151 - plaintext (ref) (class): received headers match up list context get_header
> ok 152 - correct stringification of plaintext (ref) (class); same as reference object
> ok 153 - correct body length for plaintext (ref) (class)
> ok 154 - can't alter an unwrapped string
> ok 155 - (no test; can't check altering unalterable alteration)
> ok 156 - Subject OK with Email::Abstract
> ok 157 - no exception on altering object via Email::Abstract
> ok 158 - Email::Abstract: received headers match up list context get_header
> ok 159 - correct stringification of Email::Abstract; same as reference object
> ok 160 - correct body length for Email::Abstract
> ok 161 - no exception on altering object via Email::Abstract
> ok 162 - set subject and body, restringified ok with Email::Abstract
> ok 163 - trying to wrap a wrapper returns the wrapper; it doesn't re-wrap
> ok 164 # skip MIME::Entity: unavailable
> # testing Email::MIME with 1.937
> ok 165 - minimal body test on MIME::Entity
> # Looks like you failed 6 tests of 165.
> Dubious, test returned 6 (wstat 1536, 0x600)
> Failed 6/165 subtests 
> 	(less 47 skipped subtests: 112 okay)
> 
> Test Summary Report
> -------------------
> t/abstractions.t (Wstat: 1536 Tests: 165 Failed: 6)
>   Failed tests:  76-77, 84-85, 91-92
>   Non-zero exit status: 6
> Files=1, Tests=165,  0 wallclock secs ( 0.04 usr  0.01 sys +  0.16 cusr  0.00 csys =  0.21 CPU)
> Result: FAIL

**Comment by rjbs** [comment]
Mail::Internet 2.17 was broken.  2.18 works again.

https://metacpan.org/changes/distribution/MailTools#L6
