### ISSUE TITLE
Can't install in perl v5.20.2

### ISSUE THREAD

**Issue by goodole** [rjbs/Email-Abstract#8]
perl Makefile.PL && make && make test

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Email::Abstract
Writing MYMETA.yml and MYMETA.json
cp lib/Email/Abstract/EmailMIME.pm blib/lib/Email/Abstract/EmailMIME.pm
cp lib/Email/Abstract/MailInternet.pm blib/lib/Email/Abstract/MailInternet.pm
cp lib/Email/Abstract/EmailSimple.pm blib/lib/Email/Abstract/EmailSimple.pm
cp lib/Email/Abstract/Plugin.pm blib/lib/Email/Abstract/Plugin.pm
cp lib/Email/Abstract/MIMEEntity.pm blib/lib/Email/Abstract/MIMEEntity.pm
cp lib/Email/Abstract.pm blib/lib/Email/Abstract.pm
cp lib/Email/Abstract/MailMessage.pm blib/lib/Email/Abstract/MailMessage.pm
Manifying blib/man3/Email::Abstract.3p
Manifying blib/man3/Email::Abstract::EmailMIME.3p
Manifying blib/man3/Email::Abstract::EmailSimple.3p
Manifying blib/man3/Email::Abstract::MIMEEntity.3p
Manifying blib/man3/Email::Abstract::MailInternet.3p
Manifying blib/man3/Email::Abstract::MailMessage.3p
Manifying blib/man3/Email::Abstract::Plugin.3p
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-report-prereqs.t .. # 
# Versions for all modules listed in MYMETA.json (including optional ones):
# 
# === Configure Requires ===
# 
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 6.98
# 
# === Build Requires ===
# 
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 6.98
# 
# === Test Requires ===
# 
#     Module              Want     Have
#     ------------------- ---- --------
#     ExtUtils::MakeMaker  any     6.98
#     File::Spec           any  3.48_02
#     Test::More          0.96 1.302015
#     lib                  any     0.63
# 
# === Test Recommends ===
# 
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150005
# 
# === Runtime Requires ===
# 
#     Module             Want   Have
#     ----------------- ----- ------
#     Carp                any 1.3301
#     Email::Simple     1.998  2.210
#     MRO::Compat         any   0.12
#     Module::Pluggable   1.5    5.2
#     Scalar::Util        any   1.38
#     strict              any   1.08
#     warnings            any   1.23
# 
t/00-report-prereqs.t .. ok   
t/abstractions.t ....... 1/165 # testing Email::MIME with 1.937
# testing Email::Simple with 2.210
# testing Mail::Internet with 2.17

#   Failed test 'correct stringification of Mail::Internet; same as reference object'
#   at t/lib/Test/EmailAbstract.pm line 74.
#          got: ''
#     expected: 'Joanna, All
# 
# Thanks. I got the following response from Fred Tydeman.
# 
# On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
# > Sun's expert in this area after some discussions with a colleague
# > outside of Sun concluded that for lround, to align with both C99 and SUS
# > changes of the following form were necessary:
# > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
# 
# -----
# Andrew Josey                                The Open Group  
# Austin Group Chair                          Apex Plaza,Forbury Road,
# Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
# Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'

#   Failed test 'correct body length for Mail::Internet'
#   at t/lib/Test/EmailAbstract.pm line 80.
#          got: '0'
#     expected: '749'

#   Failed test 'correct stringification of Mail::Internet; same as reference object'
#   at t/lib/Test/EmailAbstract.pm line 74.
#          got: ''
#     expected: 'Joanna, All
# 
# Thanks. I got the following response from Fred Tydeman.
# 
# On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
# > Sun's expert in this area after some discussions with a colleague
# > outside of Sun concluded that for lround, to align with both C99 and SUS
# > changes of the following form were necessary:
# > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
# 
# -----
# Andrew Josey                                The Open Group  
# Austin Group Chair                          Apex Plaza,Forbury Road,
# Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
# Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'

#   Failed test 'correct body length for Mail::Internet'
#   at t/lib/Test/EmailAbstract.pm line 80.
#          got: '0'
#     expected: '749'

#   Failed test 'correct stringification of Mail::Internet; same as reference object'
#   at t/lib/Test/EmailAbstract.pm line 74.
#          got: ''
#     expected: 'Joanna, All
# 
# Thanks. I got the following response from Fred Tydeman.
# 
# On Nov 13,  9:56am in "Re: Defect in XBD lr", Joanna Farley wrote:
# > Sun's expert in this area after some discussions with a colleague
# > outside of Sun concluded that for lround, to align with both C99 and SUS
# > changes of the following form were necessary:
# > this line of text is really long and no one need worry about it but why was such a long text chosen to begin with i mean really??
# 
# -----
# Andrew Josey                                The Open Group  
# Austin Group Chair                          Apex Plaza,Forbury Road,
# Email: a.josey@opengroup.org                Reading,Berks.RG1 1AX,England
# Tel:   +44 118 9508311 ext 2250             Fax: +44 118 9500110'

#   Failed test 'correct body length for Mail::Internet'
#   at t/lib/Test/EmailAbstract.pm line 80.
#          got: '0'
#     expected: '749'
# testing Email::MIME with 1.937
# Looks like you failed 6 tests of 165.
t/abstractions.t ....... Dubious, test returned 6 (wstat 1536, 0x600)
Failed 6/165 subtests 
        (less 47 skipped subtests: 112 okay)
t/subclass.t ........... ok   
t/unknown.t ............ ok   

Test Summary Report
-------------------
t/abstractions.t     (Wstat: 1536 Tests: 165 Failed: 6)
  Failed tests:  76-77, 84-85, 91-92
  Non-zero exit status: 6
Files=4, Tests=174,  1 wallclock secs ( 0.08 usr  0.03 sys +  0.72 cusr  0.17 csys =  1.00 CPU)
Result: FAIL
Failed 1/4 test programs. 6/174 subtests failed.
*** Error 255 in /root/.cpan/build/Email-Abstract-3.008-v0YVGi (Makefile:893 'test_dynamic')

**Comment by rjbs** [comment]
Mail::Internet 2.17 was broken.  2.18 works again.

https://metacpan.org/changes/distribution/MailTools#L6
